services:
  - name: chrome-remote-desktop
    plan: starter
    env:
      - key: CRP
        from_secret: DISPLAY= /opt/google/chrome-remote-desktop/start-host --code="4/0AeaYSHAklqrbH3Wj44Xio7IRq1d9gBELfodRrALKF4NG0K-qP7nhp3NE7TwBsoCI1i2sqg" --redirect-url="https://remotedesktop.google.com/_/oauthredirect" --name=$(hostname)
      - key: PIN
        from_secret: 123456
      - key: AUTOSTART
        value: "true"
