services:
  - name: my-service
    envVars:
      USERNAME: user
      PASSWORD: root
      CRP: "DISPLAY= /opt/google/chrome-remote-desktop/start-host --code="4/0AeaYSHC2lC6Yf6IEXdSRpzUU1Gz1JHrNXLJTLEKI4Hv5qM6hRRAA-TzgUINPqK-BvTJd8g" --redirect-url="https://remotedesktop.google.com/_/oauthredirect" --name=$(hostname)"
      PIN: 123456
      AUTOSTART: "True"
